import Head from "next/head";
import { Container, Button, Flex, Center } from "@chakra-ui/react";
import NextLink from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Porfis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Flex
          height={"100vh"}
          alignContent={"center"}
          justifyContent={"center"}
        >
          <Center>
            <NextLink href="/invitation">
              <Button bg="red.600" color="white">
                Click Me
              </Button>
            </NextLink>
          </Center>
        </Flex>
      </Container>
    </div>
  );
}
